print('hello world,hello vscode,hello github')
print('hello world,hello vscode,hello github----V1.0')
print('hello world,hello vscode,hello github----V1.1')
print('hello world,hello vscode,hello github----V1.2')
print('hello world,hello vscode,hello github----V1.3')